I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 352, in script
    c "Oh uhm…yeah sure. There’s no reason to hide from you anymore, so…"
Exception: Sayer 'c' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 352, in script
    c "Oh uhm…yeah sure. There’s no reason to hide from you anymore, so…"
  File "C:\Users\tyly0\Desktop\Ren'Py\renpy-7.4.11-sdk/renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\tyly0\Desktop\Ren'Py\renpy-7.4.11-sdk/renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'c' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Asterion Fanfic 1.0
Tue Mar 29 20:00:48 2022
